#include "hooks/function_map.h"

#include <algorithm>
#include <array>

namespace sw2e::hooks {
namespace {

constexpr std::array<FunctionInfo, 112> kKnownFunctions{{
    {0x8210D9F8, "sub_8210D9F8", "archive LZP2 postprocess", FunctionConfidence::Confirmed,
     "Called after archive sector reads; checks byte-swapped LZP2 magic 0x32505A4C, copies compressed data to scratch, and calls the in-place LZP2 decoder."},
    {0x8210DA80, "sub_8210DA80", "archive table shutdown", FunctionConfidence::Confirmed,
     "Frees the three runtime archive entry tables and closes their open archive handles."},
    {0x8210DBD0, "sub_8210DBD0", "archive entry byte-size lookup",
     FunctionConfidence::Confirmed,
     "Returns runtime archive record field +8 for packed archive id: low 26 bits entry index, high bits archive selector."},
    {0x8210DC18, "sub_8210DC18", "archive entry sector-count lookup",
     FunctionConfidence::Confirmed,
     "Returns runtime archive record field +4, the allocated sector count used by archive reads."},
    {0x8210E0D8, "sub_8210E0D8", "LINKDATA archive table initializer",
     FunctionConfidence::Confirmed,
     "IDA xrefs from LINKDATA_BNS.LNK/IDX path table; opens each LNK/IDX pair, reads IDX, allocates 20-byte runtime records, and expands sector/size fields."},
    {0x8210E4A8, "sub_8210E4A8", "archive handle selector", FunctionConfidence::Confirmed,
     "Chooses either a per-file temporary handle for special 10000-10255 ids or the open archive handle selected by packed archive id bits."},
    {0x8210E528, "sub_8210E528", "archive entry sector read", FunctionConfidence::Confirmed,
     "Core LINKDATA entry reader: decodes packed archive id, seeks to sector offsets, reads sector-aligned payloads, optionally mirrors to cache, then runs LZP2 postprocess."},
    {0x8210E958, "sub_8210E958", "archive async entry read enqueue",
     FunctionConfidence::Confirmed,
     "Queues a packed archive entry read into the background archive worker when the high-level asset wrapper requests non-immediate loading."},
    {0x8210EAE8, "sub_8210EAE8", "archive read into caller buffer wrapper",
     FunctionConfidence::Confirmed,
     "Ensures archive system state, then either queues or synchronously reads a packed archive entry into a caller-provided output buffer."},
    {0x8210EB40, "sub_8210EB40", "archive allocate-and-read wrapper",
     FunctionConfidence::Confirmed,
     "Allocates a buffer sized from archive metadata or caller sector count, then queues or synchronously reads the packed archive entry."},
    {0x8210EF50, "sub_8210EF50", "archive filesystem bootstrap", FunctionConfidence::Confirmed,
     "Initializes file/archive critical sections and calls the LINKDATA archive table initializer before async file system setup."},
    {0x8210F1F8, "sub_8210F1F8", "storage prompt caller", FunctionConfidence::Observed,
     "Project hook seeds dummy HDD device id 1 before running the selector path."},
    {0x82110570, "sub_82110570", "storage/profile flow", FunctionConfidence::Observed,
     "Shows the storage-required notice when device id is -1; project hook seeds id 1 first."},
    {0x82110D40, "sub_82110D40", "save game data write flow", FunctionConfidence::Confirmed,
     "IDA decompile shows XamContentCreateEx/open, writes save:\\SW2Empires.dat through the game file wrapper, loads archive entry 0xDDC for the thumbnail, and calls XamContentSetThumbnail."},
    {0x821EDA68, "sub_821EDA68", "runtime-discovered transition helper",
     FunctionConfidence::Observed,
     "Added to the manifest after an invalid-function fatal during the menu transition."},
    {0x82116600, "sub_82116600", "LZP2 decoder", FunctionConfidence::Confirmed,
     "Game decoder for LZP2 streams: literal run when control <0x40, RLE when bit 0x40 is set, back-reference when bit 0x80 is set, terminates on control byte 0."},
    {0x82116898, "sub_82116898", "WMV movie playback flow", FunctionConfidence::Confirmed,
     "Builds d:\\data\\movie\\MEV%02u.wmv, opens the movie player, steps callbacks and draw work until playback exits. Relevant to the boot movie workaround."},
    {0x8215D4C0, "sub_8215D4C0", "weapon tables initializer", FunctionConfidence::Confirmed,
     "Source path Weapon.cpp. Loads archive entries 0x62A and 0x62B; entry 0x62B is counted as 0x30-byte records, then 160 0xB0-byte runtime weapon slots and 141 status bytes are initialized."},
    {0x82200AA8, "sub_82200AA8", "free mode setup table loader",
     FunctionConfidence::Confirmed,
     "Source path emp_free_setup.cpp. Loads archive entries 0x78 and 0x79, then initializes Japan-map/menu helpers for Free Mode setup."},
    {0x8220B210, "sub_8220B210", "edit state asset initializer",
     FunctionConfidence::Confirmed,
     "Source path StateEdit.cpp. Loads archive entry 0x80, initializes edit/new-officer character selections, and touches weapon/character setup helpers."},
    {0x82224730, "sub_82224730", "startup tables loader",
     FunctionConfidence::Confirmed,
     "Source path StateStartUp.cpp. Loads archive entries 0x76, 0x79, and 0x78 before startup/menu state continues."},
    {0x82257938, "sub_82257938", "scenario control table loader",
     FunctionConfidence::Confirmed,
     "Source path sc_ctrl.cpp. Loads archive entry 0x44 through the high-level asset wrapper, stores a count/pointer pair at 0x827A6B70/0x827A6B74, initializes scenario control helpers, and clears scenario globals."},
    {0x82260B98, "sub_82260B98", "scenario message section blob loader",
     FunctionConfidence::Confirmed,
     "Loads archive entry 0x41, treats it as a seven-section offset/size blob, and wires message/string subsections including 0x2A and 0x11 indexed groups."},
    {0x82262678, "sub_82262678", "scenario auxiliary table loader",
     FunctionConfidence::Confirmed,
     "Loads archive entry 0x42 through the high-level asset wrapper and stores base/base+4 globals at 0x827A6B7C/0x827A6B80; the entry is a counted 595-row table with 0x2C-byte rows."},
    {0x8226A970, "sub_8226A970", "relay camera resource loader",
     FunctionConfidence::Confirmed,
     "Source path RelayCamera.cpp. Clears relay-camera globals and loads archive entry 0x4D into the camera resource pointer."},
    {0x8227AD30, "sub_8227AD30", "battle stage scene cleanup",
     FunctionConfidence::Observed,
     "Calls the stage subasset table cleanup and frees stage-scene buffers during battle-stage teardown."},
    {0x8227AAB0, "sub_8227AAB0", "stage set first-two bundle loader",
     FunctionConfidence::Confirmed,
     "Loads the first two entries of a stride-3 stage set. Normal path uses 3*stage+2856 and +2857; alternate override path uses 3*stage+2937 and +2938."},
    {0x8227AE00, "sub_8227AE00", "battle stage scene bootstrap",
     FunctionConfidence::Confirmed,
     "Initializes stage-scene globals, fixes offsets in a stage metadata table, loads the three-entry stage set, then wires terrain and placement systems."},
    {0x82286950, "sub_82286950", "stage subasset table allocator",
     FunctionConfidence::Confirmed,
     "Stores the stage bundle's subfile count, allocates a 32-byte-per-subfile runtime table, and clears it before subfile instantiation."},
    {0x822869D8, "sub_822869D8", "stage metadata row lookup",
     FunctionConfidence::Confirmed,
     "Returns a 100-byte stage metadata row from the global stage table, with special-case rows for modes 2 and 3."},
    {0x82286A70, "sub_82286A70", "stage subasset table cleanup",
     FunctionConfidence::Confirmed,
     "Releases instantiated stage subassets and frees the runtime stage subasset table."},
    {0x82286B30, "sub_82286B30", "stage bundle subfile instantiator",
     FunctionConfidence::Confirmed,
     "Walks the loaded stage bundle offset table, converts subfile offsets to pointers, and creates runtime objects for each stage subasset."},
    {0x82286D10, "sub_82286D10", "stage bundle loader",
     FunctionConfidence::Confirmed,
     "Selects the current stage id and loads a stride-3 stage bundle entry: normal stages use 3*stage+2858, alternate override stages use 3*stage+2939."},
    {0x82286EE0, "sub_82286EE0", "early battle table loader",
     FunctionConfidence::Observed,
     "Loads one of entries 146-150 before battle-stage work; likely an early table/config preload rather than direct geometry."},
    {0x8234D7B8, "sub_8234D7B8", "start transition caller", FunctionConfidence::Observed,
     "On the call stack while moving from title to storage/gameplay."},
    {0x8234C7A8, "sub_8234C7A8", "title-task locked dispatch caller",
     FunctionConfidence::Observed,
     "Freeze stack caller of the global-locked title-task dispatch wrapper."},
    {0x8234D948, "sub_8234D948", "title-task wait caller", FunctionConfidence::Observed,
     "Freeze stack caller of the multiple-object wait wrapper during title/menu transition."},
    {0x8234E500, "sub_8234E500", "start transition", FunctionConfidence::Observed,
     "On the call stack while moving from title to storage/gameplay."},
    {0x8234E688, "sub_8234E688", "runtime-discovered start transition", FunctionConfidence::Observed,
     "Added to the manifest after runtime discovery."},
    {0x823523D0, "sub_823523D0", "storage selector wrapper candidate", FunctionConfidence::Observed,
     "Tiny wrapper around XamShowDeviceSelectorUI; candidate hook point for storage selection."},
    {0x82351CA0, "sub_82351CA0", "file close wrapper", FunctionConfidence::Confirmed,
     "Thin NtClose wrapper returning 1 on success; used by archive initialization and save/profile file paths."},
    {0x82351CE8, "sub_82351CE8", "file read wrapper", FunctionConfidence::Confirmed,
     "NtReadFile wrapper with optional overlapped/offset support; archive init uses it to read whole IDX payloads."},
    {0x82351F78, "sub_82351F78", "file create/open wrapper", FunctionConfidence::Confirmed,
     "RtlInitAnsiString + NtCreateFile wrapper for game:\\ paths; IDA shows archive init using it for LINKDATA_BNS and runtime hooks log the same calls."},
    {0x82352160, "sub_82352160", "file write wrapper", FunctionConfidence::Confirmed,
     "NtWriteFile wrapper mirroring the read wrapper; useful for save/cache write hooks and archive cache-file tracing."},
    {0x82352288, "sub_82352288", "file seek wrapper", FunctionConfidence::Confirmed,
     "NtQueryInformationFile/NtSetInformationFile wrapper for absolute/current/end seeking; archive init seeks IDX handles before reading."},
    {0x823523F8, "sub_823523F8", "file size query wrapper", FunctionConfidence::Confirmed,
     "Queries file size via the shared file status helper; archive init rounds this to 0x800 before reading IDX data."},
    {0x82347750, "sub_82347750", "archive asset load wrapper",
     FunctionConfidence::Confirmed,
     "High-level archive asset loader used by stage, character, UI, and table systems. It maps source 0/1/2 to archive selector bits, allocates or uses caller buffers, then queues or synchronously reads an entry."},
    {0x823477F8, "sub_823477F8", "asset system state poll wrapper",
     FunctionConfidence::Observed,
     "Tiny wrapper returning whether the asset system state helper equals 1; stage bundle load calls it after loading bundled data."},
    {0x822A85C0, "sub_822A85C0", "Japan map resource selector",
     FunctionConfidence::Confirmed,
     "Source path JapanMap.cpp. Resets Japan-map UI globals, selects an archive entry from a table using the map variant id, then waits for the asset system."},
    {0x82353A98, "sub_82353A98", "xam message-box wrapper", FunctionConfidence::Observed,
     "Allocates an event and calls XamShowMessageBoxUIEx with title/body/button string pointers."},
    {0x82353B50, "sub_82353B50", "localized wide-string lookup", FunctionConfidence::Observed,
     "Builds heap-owned UTF-16 strings from an indexed language table."},
    {0x82353BF8, "sub_82353BF8", "video-mode warning message flow", FunctionConfidence::Observed,
     "Checks executable privilege, AV pack, language/config, then calls the message-box wrapper."},
    {0x82354D80, "sub_82354D80", "launch/start path", FunctionConfidence::Observed,
     "On the title/start call chain."},
    {0x82351CD8, "sub_82351CD8", "single-object wait helper", FunctionConfidence::Observed,
     "Calls the single-object wait wrapper; seen in frozen cleanup worker threads."},
    {0x823540B0, "sub_823540B0", "NtWaitForSingleObjectEx wrapper",
     FunctionConfidence::Observed,
     "Wait helper immediately above the kernel NtWaitForSingleObjectEx import in freeze stacks."},
    {0x82355400, "sub_82355400", "guest heap coalescer", FunctionConfidence::Confirmed,
     "Hit a bad neighbor-block pointer during boot; retained as a heap lifecycle marker."},
    {0x82356300, "sub_82356300", "guest heap resize/split", FunctionConfidence::Confirmed,
     "Hit an invalid split-block header pointer during title transition; retained as a heap lifecycle marker."},
    {0x8235AB38, "sub_8235AB38", "draw state command burst",
     FunctionConfidence::Confirmed,
     "Called from the command-stream drain path; crashed writing state words into a read-only command page."},
    {0x8235AC30, "sub_8235AC30", "draw state setup companion",
     FunctionConfidence::Observed,
     "Adjacent setup helper after the draw state command burst."},
    {0x8235CC48, "sub_8235CC48", "transient draw packet builder",
     FunctionConfidence::Confirmed,
     "Hit a stale transient buffer after the missing WMV path; project hook skips stale draw cursors."},
    {0x82361B70, "sub_82361B70", "draw state/quad command builder",
     FunctionConfidence::Confirmed,
     "Movie/title transition crash wrote a state-word burst into a read-only command page."},
    {0x82362968, "sub_82362968", "draw state builder caller",
     FunctionConfidence::Observed,
     "Companion draw-state path near sub_82361B70; observed in generated call graph."},
    {0x82364248, "sub_82364248", "command stream drain caller",
     FunctionConfidence::Observed,
     "Caller around command-stream cleanup/drain work; appeared above sub_82365290 after the stale page guard."},
    {0x82365290, "sub_82365290", "texture/resolve packet page helper",
     FunctionConfidence::Confirmed,
     "Writes paired 44-byte command packets and can receive stale read-only command pages after movie/title transitions."},
    {0x82365428, "sub_82365428", "texture/resolve packet companion",
     FunctionConfidence::Confirmed,
     "Companion helper called from the command-stream flush path; observed after a read-only packet page crash."},
    {0x8235D660, "sub_8235D660", "movie/draw state submitter",
     FunctionConfidence::Confirmed,
     "Repeated stale command-stream crashes while leaving movie/title-transition screens."},
    {0x8235E3B8, "sub_8235E3B8", "movie vertex-stream caller",
     FunctionConfidence::Observed,
     "Immediate caller of sub_82369BC0 when the movie/title path hit a stale vertex output page."},
    {0x8235EEB0, "sub_8235EEB0", "movie texture packet submitter",
     FunctionConfidence::Confirmed,
     "Crashed after MEV15 was restored while writing a movie/title-transition command packet."},
    {0x8235F3B0, "sub_8235F3B0", "movie texture submit caller",
     FunctionConfidence::Observed,
     "Immediate caller of the movie texture packet submitter in the MEV15-restored crash."},
    {0x82365A98, "sub_82365A98", "command stream submit helper",
     FunctionConfidence::Confirmed,
     "Command-stream helper around the flush/reset path; observed immediately before GPU packet-count overflow."},
    {0x82365C40, "sub_82365C40", "command stream flush/reset",
     FunctionConfidence::Confirmed,
     "Flush path for the draw command cursor; project guard resets stale read-only cursors."},
    {0x82369820, "sub_82369820", "variable packet writer",
     FunctionConfidence::Confirmed,
     "Guarded after the skipped/movie path left packet output on a read-only guest page."},
    {0x82369BC0, "sub_82369BC0", "movie vertex-stream packet writer",
     FunctionConfidence::Confirmed,
     "Variable-length stream writer; crashed writing movie/title vertex data into a read-only mapped page."},
    {0x82369D30, "sub_82369D30", "movie vertex-stream packet companion",
     FunctionConfidence::Observed,
     "Adjacent generated helper called by later vertex-stream setup paths."},
    {0x8236B8B8, "sub_8236B8B8", "PIX trace capture state machine",
     FunctionConfidence::Observed,
     "Reached by PIX trace/capture strings including PIX!Trace, PIX!Gpu, crashdump.pix2, and capture begin/end messages; likely renderer diagnostic capture scaffolding."},
    {0x8236BBF8, "sub_8236BBF8", "renderer debug command parser",
     FunctionConfidence::Observed,
     "Switches on the byte at input+4 for single-letter commands a/c/d/f/g/m/p/t/x and writes a response with sprintf; project hook logs command and response buffers."},
    {0x8236BE60, "sub_8236BE60", "PIX performance marker callback",
     FunctionConfidence::Observed,
     "Registered by the PIX diagnostic registration path as callback id 47; tracks render event begin/end bits, flushes selected command stream events, and emits timing counters through a PIX-style output helper."},
    {0x8236C020, "sub_8236C020", "PIX diagnostic callback registration",
     FunctionConfidence::Confirmed,
     "Registers sw2e_renderer_debug_command_parser as diagnostic command 28 and registers sw2e_pix_performance_marker_callback as callback id 47 during graphics config initialization."},
    {0x8236D8F0, "sub_8236D8F0", "guest debug print formatter",
     FunctionConfidence::Confirmed,
     "Formats a 260-byte stack message with __vsnprintf and sends it to the Xbox DbgPrint import."},
    {0x8236D978, "sub_8236D978", "guest debug callback logger",
     FunctionConfidence::Confirmed,
     "Formats diagnostic text, dispatches it through a callback stored in the logger context when present, and falls back to DbgPrint otherwise."},
    {0x8236DCE0, "sub_8236DCE0", "graphics device diagnostic report builder",
     FunctionConfidence::Observed,
     "Builds a graphics/device diagnostic report through callback helpers and the guest logger wrapper."},
    {0x8236DF60, "sub_8236DF60", "graphics init diagnostic trap path",
     FunctionConfidence::Observed,
     "Emits graphics initialization diagnostics, calls the report builder, and traps if a required device pointer is missing."},
    {0x8236E780, "sub_8236E780", "graphics config probe and init path",
     FunctionConfidence::Observed,
     "Calls ExGetXConfigSetting, probes render/device state, and reaches the graphics diagnostics cluster during initialization."},
    {0x823AB610, "sub_823AB610", "movie scene/player step",
     FunctionConfidence::Observed,
     "On the call stack above movie packet submission after restoring MEV15."},
    {0x823ACC50, "sub_823ACC50", "movie frame bulk copy/submitter",
     FunctionConfidence::Confirmed,
     "Caller of the shared copy helper when movie/title data tried to copy into a stale mapped page."},
    {0x82385138, "sub_82385138", "title-task vtable+8 locked dispatch",
     FunctionConfidence::Confirmed,
     "Blocked on the 0x8258A5B4 global critical section in a frozen Empire Mode transition."},
    {0x82385210, "sub_82385210", "title vtable dispatch wrapper", FunctionConfidence::Confirmed,
     "Crashed on stale object/vtable pointers during title transition; retained as a title-object marker."},
    {0x82385800, "sub_82385800", "title-task locked lookup", FunctionConfidence::Confirmed,
     "Blocked on the same title-task global critical section while resolving queued work."},
    {0x823859A8, "sub_823859A8", "KeWaitForMultipleObjects wrapper",
     FunctionConfidence::Confirmed,
     "Multiple frozen worker threads were waiting here during the Empire Mode transition."},
    {0x82386910, "sub_82386910", "title cleanup/destructor", FunctionConfidence::Confirmed,
     "Hit stale vtable/list pointers and a stale-object cleanup loop during title transition."},
    {0x82386F50, "sub_82386F50", "title-task worker wait loop", FunctionConfidence::Observed,
     "Worker wait path that appears beside the cleanup deadlock in debugger stacks."},
    {0x82387138, "sub_82387138", "title cleanup caller", FunctionConfidence::Observed,
     "Caller of the title cleanup routine."},
    {0x823887B8, "sub_823887B8", "runtime-discovered helper", FunctionConfidence::Observed,
     "Added to the manifest after runtime discovery."},
    {0x82391A10, "sub_82391A10", "runtime-discovered helper", FunctionConfidence::Observed,
     "Added to the manifest after runtime discovery."},
    {0x8249E854, "__imp__XamInputGetState", "xam controller state import",
     FunctionConfidence::Confirmed,
     "Project hook merges real user-0 input with optional staged boot pulses for smoke tests."},
    {0x8249EBE4, "__imp__DbgPrint", "xbox debug print import",
     FunctionConfidence::Confirmed,
     "Project hook mirrors guest developer diagnostics into the PC runtime log; this is the best current path for enabling surviving debug output."},
    {0x8249E874, "__imp__XamInputGetKeystrokeEx", "xam controller event import",
     FunctionConfidence::Observed,
     "Project hook can optionally synthesize boot Start/A key events for smoke tests."},
    {0x8249E724, "__imp__XamShowDeviceSelectorUI", "xam storage device selector import",
     FunctionConfidence::Observed,
     "ReXGlue dummy HDD path writes device id 1 and returns success via overlapped completion."},
    {0x8248E500, "sub_8248E500", "guest memcpy helper", FunctionConfidence::Confirmed,
     "Shared structure/copy helper; observed as the callee of the movie frame bulk-copy crash."},
    {0x8249E7D4, "__imp__XamContentCreateEx", "xam content create import",
     FunctionConfidence::Observed,
     "ReXGlue content manager can create/open saved-game content under the user data root."},
    {0x8249E7E4, "__imp__XamContentClose", "xam content close import",
     FunctionConfidence::Observed,
     "Content close call on the save-container path; logged to bracket save lifecycle."},
    {0x8249E7F4, "__imp__XamContentSetThumbnail", "xam content thumbnail import",
     FunctionConfidence::Observed,
     "Save-container thumbnail write; useful marker before file writes and flushes."},
    {0x8249E824, "__imp__XamContentGetDeviceData", "xam content device data import",
     FunctionConfidence::Observed, "Reports the runtime dummy HDD/ODD devices."},
    {0x8249E884, "__imp__XamShowMessageBoxUIEx", "xam message-box import",
     FunctionConfidence::Observed,
     "Runtime stub currently logs once and returns success without drawing a dialog."},
    {0x8249E914, "__imp__NtClose", "kernel close import", FunctionConfidence::Observed,
     "File/content handle close on save and load paths; logged to catch stale handle flow."},
    {0x8249E974, "__imp__NtCreateFile", "kernel file create/open import",
     FunctionConfidence::Observed,
     "Logs guest file paths and returned handles so archive/content access can be mapped."},
    {0x8249E924, "__imp__NtWaitForSingleObjectEx", "kernel wait import",
     FunctionConfidence::Observed,
     "Potential freeze marker when save/profile code waits for an event or file operation."},
    {0x8249E934, "__imp__NtReadFile", "kernel file read import", FunctionConfidence::Observed,
     "Reads save/profile files from the selected content container."},
    {0x8249E994, "__imp__NtWriteFile", "kernel file write import", FunctionConfidence::Observed,
     "Writes save/profile files; logged around manual save/settings freezes."},
    {0x8249E9D4, "__imp__NtOpenFile", "kernel file open import",
     FunctionConfidence::Observed,
     "Logs guest file paths and returned handles; primary runtime probe for game archive reads."},
    {0x8249EAA4, "__imp__NtFlushBuffersFile", "kernel file flush import",
     FunctionConfidence::Observed, "Flushes save data before close/wait completion."},
    {0x8249EEE4, "__imp__XamUserReadProfileSettings", "xam profile settings import",
     FunctionConfidence::Observed, "Profile import used on the save/profile path."},
}};

}  // namespace

std::span<const FunctionInfo> KnownFunctions() {
  return kKnownFunctions;
}

const FunctionInfo* FindKnownFunction(uint32_t address) {
  const auto it = std::ranges::find_if(kKnownFunctions, [address](const FunctionInfo& info) {
    return info.address == address;
  });
  return it == kKnownFunctions.end() ? nullptr : &*it;
}

std::string_view ConfidenceName(FunctionConfidence confidence) {
  switch (confidence) {
    case FunctionConfidence::Generated:
      return "generated";
    case FunctionConfidence::Observed:
      return "observed";
    case FunctionConfidence::Confirmed:
      return "confirmed";
  }
  return "unknown";
}

}  // namespace sw2e::hooks
